upstream frontend {
    server frontend-container:3000;
}

upstream backend {
    server backend:9000;
}

server {
    listen 80;
    server_name frontend;
    server_name backend;

    location / {
        proxy_set_header Host $host;
        proxy_pass http://frontend;
    }

    location /engagingUsers {
        proxy_set_header Host $host;
        proxy_pass http://backend/engagingUsers;
    }

    location /avgNewUsers {
        proxy_set_header Host $host;
        proxy_pass http://backend/avgNewUsers;
    }

    location /avgNewPosts {
        proxy_set_header Host $host;
        proxy_pass http://backend/avgNewPosts;
    }

    location /popularPosts {
        proxy_set_header Host $host;
        proxy_pass http://backend/popularPosts;
    }

    location /commonHashtags {
        proxy_set_header Host $host;
        proxy_pass http://backend/commonHashtags;
    }

    location /postTimes {
        proxy_set_header Host $host;
        proxy_pass http://backend/postTimes;
    }

    location /geoData {
        proxy_set_header Host $host;
        proxy_pass http://backend/geoData;
    }

    location /avgVideoLengths {
        proxy_set_header Host $host;
        proxy_pass http://backend/avgVideoLengths;
    }

    location /avgDescriptionLength {
        proxy_set_header Host $host;
        proxy_pass http://backend/avgDescriptionLength;
    }

    location /totalUniquePosts {
        proxy_set_header Host $host;
        proxy_pass http://backend/totalUniquePosts;
    }

     location /totalUniqueUsers {
        proxy_set_header Host $host;
        proxy_pass http://backend/totalUniquePosts;
    }
}
